In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("50_Startups.csv")

In [19]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [21]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
X_train

array([[0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [31]:
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)

In [33]:
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [35]:
y_pred = regressor.predict(X_test)

In [37]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_pred), 1)), 1))

[[103669.135 103282.38 ]
 [133310.358 144259.4  ]
 [136197.222 146121.95 ]
 [ 81563.321  77798.83 ]
 [183960.885 191050.39 ]
 [114786.017 105008.31 ]
 [ 76475.731  81229.06 ]
 [100724.345  97483.56 ]
 [113105.19  110352.25 ]
 [162041.611 166187.94 ]]


In [39]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9658739721928109

In [43]:
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_pred), 1)), 1))
r2_score(y_test, y_pred)

[[103479.8684 103282.38  ]
 [135384.9225 144259.4   ]
 [136751.8368 146121.95  ]
 [ 80760.2823  77798.83  ]
 [183973.8537 191050.39  ]
 [113171.1923 105008.31  ]
 [ 71153.4241  81229.06  ]
 [ 99464.1182  97483.56  ]
 [110992.6646 110352.25  ]
 [169041.1514 166187.94  ]]


0.968248553273118

In [45]:
regressor.feature_importances_

array([0.00172525, 0.0010161 , 0.00103852, 0.90935213, 0.0053113 ,
       0.08155669])

In [51]:
regressor.feature_names_in_

AttributeError: 'RandomForestRegressor' object has no attribute 'feature_names_in_'

In [53]:
sum(regressor.feature_importances_)

1.0

In [55]:
regressor.predict(np.array([[0.0, 1.0, 0.0, 32323, 75000, 1]]))

array([72583.0781])

In [65]:
from sklearn.metrics import mean_absolute_error

In [67]:
mae = mean_absolute_error(y_test, y_pred)

In [69]:
mae

5219.27701000002

Extra reading - cross validation